USE shopping_cart;
INSERT INTO items
(name, price, is_imported, category, image_url)
VALUES
('The Great Gatsby', 10.61, false, 'Book', '../../assets/images/greatgatsby.jpg'),
('To Kill A Mockingbird', 7.33, false, 'Book', '../../assets/images/tokillamockingbird.jpg'),
('The Alchemist', 10.90, false, 'Book', '../../assets/images/thealchemist.jpg'),
('1984', 8.15, false, 'Book', '../../assets/images/1984.jpg'),
('How To Win Friends And Influence People', 12.22, false, 'Book', '../../assets/images/howtowin.jpg'),
('Of Mice And Men', 10.04, false, 'Book', '../../assets/images/ofmiceandmen.jpg'),
('Pocky Chocolate Biscuit Sticks', 2.99, true, 'Food', '../../assets/images/pockychocolate.jpg'),
('Meiji Hello Panda Strawberry Cookies', 1.19, true, 'Food', '../../assets/images/hellopanda.jpg'),
('Kasugai Fruit Gummy Candy Assortment', 2.99, true, 'Food', '../../assets/images/fruitgummy.jpg'),
('Haribo Gold Gummy Bears', 1.99, false, 'Food', '../../assets/images/gummybears.jpg'),
('Ritter Sport Milk Chocolate With Whole Hazelnuts', 1.99, true, 'Food', '../../assets/images/rittersport.jpg'),
('Walkers Pure Butter Assorted Shortbread Cookies', 3.66, true, 'Food', '../../assets/images/walkersshortbread.jpg'),
('Genuine Bayer Aspirin, Coated Tablets, Pain Reliever', 4.49, false, 'Medicine', '../../assets/images/bayeraspirin.jpg'),
('Claritin 24-Hour Non-Drowsy Antihistamine Tablets', 12.79, false, 'Medicine', '../../assets/images/claritin.jpg'),
('Pepto-Bismol 5 Symptom Relief Liquid Original', 6.19, false, 'Medicine', '../../assets/images/peptobismol.jpg'),
('Tylenol Extra Strength Rapid Release Gels with Acetaminophen', 6.29, false, 'Medicine', '../../assets/images/tylenol.jpg'),
('Robitussin Peak Cold, Cough + Chest Congestion DM Max', 8.99, false, 'Medicine', '../../assets/images/robitussin.jpg'),
('Vicks Nyquil Cold & Flu Liquid', 9.99, false, 'Medicine', '../../assets/images/nyquil.jpg'),
('The Dark Side Of The Moon', 11.71, false, 'Music', '../../assets/images/darksideofthemoon.jpg'),
('Rumours', 9.99, false, 'Music', '../../assets/images/rumours.jpg'),
('Abbey Road', 17.09, false, 'Music', '../../assets/images/abbeyroad.jpg'),
('Back In Black', 9.66, false, 'Music', '../../assets/images/backinblack.jpg'),
('Born In The USA', 8.35, false, 'Music', '../../assets/images/bornintheusa.jpg'),
('Legend', 12.79, false, 'Music', '../../assets/images/legend.jpg'),
('Burberry Giant-Check Cashmere Scarf', 430, true, 'Luxury', '../../assets/images/burberryscarf.jpg'),
('Kate Spade New York Molly Large Leather Tote', 228, false, 'Luxury', '../../assets/images/katespadetote.jpg'),
('Ray-Ban Original Aviator Sunglasses, Golden', 168, false, 'Luxury', '../../assets/images/raybanaviator.jpg'),
('Chanel Coco Mademoiselle Eau De Parfum Intense Spray', 145, true, 'Luxury', '../../assets/images/chanelcoco.jpg'),
('Dior J\'Adore Eau De Parfum', 130, true, 'Luxury', '../../assets/images/diorjadore.jpg'),
('Tory Burch Robinson Small Saffiano Tote Bag', 298, true, 'Luxury', '../../assets/images/toryburchtote.jpg'),
('Calvin Klein Slim-Fit Solid Dress Pants', 95, false, 'Clothes', '../../assets/images/slimfitdresspants.jpg'),
('Free People Eucalyptus Cardigan', 148, false, 'Clothes', '../../assets/images/cardigan.jpg'),
('Free People Leo Henley Thermal Top', 68, false, 'Clothes', '../../assets/images/henleythermaltop.jpg'),
('Perry Ellis Mens V-Neck Sweater', 69.50, false, 'Clothes', '../../assets/images/vnecksweater.jpg'),
('Calvin Klein Pencil Skirt', 54.49, false, 'Clothes', '../../assets/images/pencilskirt.jpg'), 
('Anne Klein Pleated Sleeveless Top', 69, false, 'Clothes', '../../assets/images/ruffledsleevelesstop.jpg');